"""
Edge Security API v2  —  flat project layout
─────────────────────────────────────────────
Project root (same folder as this file):
    main.py
    requirements.txt
    Dockerfile
    yolov8n.onnx          ← generated by Docker build stage 1
    dataset/
        Mahi_admin/       ← one sub-folder per identity
            photo1.jpg
            photo2.jpg
            ...
    index.html

Cloudinary folder layout:
    surveillance/routine/   ← every 10-second heartbeat snapshot
    surveillance/alerts/    ← unknown person detected
    surveillance/weapons/   ← weapon-class object detected
"""

import gc
import glob
import io
import os
import time

import cv2
import numpy as np
from contextlib import asynccontextmanager
from PIL import Image

from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
from google import genai
import cloudinary
import cloudinary.uploader
import onnxruntime as ort

load_dotenv()

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Paths  — everything lives next to main.py in the flat layout
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BASE_DIR        = os.path.dirname(os.path.abspath(__file__))
DATASET_DIR     = os.path.join(BASE_DIR, "dataset")       # dataset/<identity>/*.jpg
YOLO_MODEL_PATH = os.path.join(BASE_DIR, "yolov8n.onnx")  # flat root

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Tunable constants
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SNAPSHOT_INTERVAL = 10     # seconds between routine Cloudinary heartbeat uploads
ALERT_COOLDOWN    = 15     # minimum seconds between alert uploads (per event type)
IDENTITY_GRACE    = 3.0    # seconds to hold a recognised identity (anti-flicker)
FACE_THRESHOLD    = 0.40   # cosine similarity floor for InsightFace buffalo_sc
                            # raise to 0.45 to reduce false positives
                            # lower to 0.32 if your admin is being missed

YOLO_CONF         = 0.50   # YOLO detection confidence threshold

# ── COCO 80 classes (index matches YOLOv8n output tensor) ────────────────────
COCO_CLASSES = [
    "person","bicycle","car","motorcycle","airplane","bus","train","truck",
    "boat","traffic light","fire hydrant","stop sign","parking meter","bench",
    "bird","cat","dog","horse","sheep","cow","elephant","bear","zebra","giraffe",
    "backpack","umbrella","handbag","tie","suitcase","frisbee","skis","snowboard",
    "sports ball","kite","baseball bat","baseball glove","skateboard","surfboard",
    "tennis racket","bottle","wine glass","cup","fork","knife","spoon","bowl",
    "banana","apple","sandwich","orange","broccoli","carrot","hot dog","pizza",
    "donut","cake","chair","couch","potted plant","bed","dining table","toilet",
    "tv","laptop","mouse","remote","keyboard","cell phone","microwave","oven",
    "toaster","sink","refrigerator","book","clock","vase","scissors",
    "teddy bear","hair drier","toothbrush",
]

# Objects that immediately escalate threat level to HIGH and trigger weapon alert
HIGH_THREAT_LABELS = {"knife", "scissors", "baseball bat"}

# ── Cloudinary folder structure ───────────────────────────────────────────────
CDN_ROUTINE = "surveillance/routine"   # heartbeat frames every 10 s
CDN_ALERTS  = "surveillance/alerts"   # unknown person snapshots
CDN_WEAPONS = "surveillance/weapons"  # weapon-class detection snapshots

# ── Gemini model fallback chain (corrected — v1 had invalid names) ────────────
GEMINI_MODELS = [
    "gemini-2.5-flash",
    "gemini-2.0-flash",
    "gemini-1.5-flash",
]

SECURITY_PROMPT = (
    "You are a professional AI security analyst reviewing a live CCTV frame. "
    "Respond in ≤ 80 words covering: "
    "① how many people are visible and their behaviour, "
    "② any suspicious objects or activities, "
    "③ overall threat rating — LOW, MEDIUM, or HIGH — with one sentence of justification."
)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Mutable globals
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

yolo_session: ort.InferenceSession = None
face_app     = None
admin_db: dict[str, list[np.ndarray]] = {}  # {folder_name: [normed_embedding, ...]}

_last_snapshot   = 0.0
_last_alert      = 0.0
_last_identity   = "Unknown"
_last_match_time = 0.0

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# YOLO  — pure ONNX, no torch dependency
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _letterbox(frame: np.ndarray, size: int = 640):
    h, w   = frame.shape[:2]
    scale  = min(size / h, size / w)
    nw, nh = int(w * scale), int(h * scale)
    resized = cv2.resize(frame, (nw, nh), interpolation=cv2.INTER_LINEAR)
    canvas  = np.full((size, size, 3), 114, dtype=np.uint8)
    canvas[:nh, :nw] = resized
    return canvas, scale


def _nms(boxes: np.ndarray, scores: np.ndarray, iou_thr: float = 0.45) -> list[int]:
    x1, y1, x2, y2 = boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]
    areas = (x2 - x1 + 1) * (y2 - y1 + 1)
    order = scores.argsort()[::-1]
    keep  = []
    while order.size > 0:
        i = order[0]; keep.append(i)
        xx1   = np.maximum(x1[i], x1[order[1:]])
        yy1   = np.maximum(y1[i], y1[order[1:]])
        xx2   = np.minimum(x2[i], x2[order[1:]])
        yy2   = np.minimum(y2[i], y2[order[1:]])
        inter = np.maximum(0.0, xx2 - xx1) * np.maximum(0.0, yy2 - yy1)
        iou   = inter / (areas[i] + areas[order[1:]] - inter)
        order = order[1:][iou < iou_thr]
    return keep


def yolo_detect(frame: np.ndarray) -> list[dict]:
    """Returns [{"label", "box":[x,y,w,h], "conf", "threat"}, ...]"""
    if yolo_session is None:
        return []

    orig_h, orig_w = frame.shape[:2]
    lb, scale = _letterbox(frame)

    blob = lb.astype(np.float32) / 255.0
    blob = blob.transpose(2, 0, 1)[np.newaxis]               # [1,3,640,640]
    inp  = yolo_session.get_inputs()[0].name
    raw  = yolo_session.run(None, {inp: blob})[0]             # [1,84,8400]
    pred = raw[0].T                                           # [8400,84]

    cls_scores = pred[:, 4:]
    confidence = cls_scores.max(axis=1)
    class_ids  = cls_scores.argmax(axis=1)

    mask = confidence > YOLO_CONF
    if not mask.any():
        return []

    p, sc, cids = pred[mask], confidence[mask], class_ids[mask]

    cx = p[:, 0] / scale;  cy = p[:, 1] / scale
    bw = p[:, 2] / scale;  bh = p[:, 3] / scale
    x1 = np.clip(cx - bw / 2, 0, orig_w).astype(int)
    y1 = np.clip(cy - bh / 2, 0, orig_h).astype(int)
    x2 = np.clip(cx + bw / 2, 0, orig_w).astype(int)
    y2 = np.clip(cy + bh / 2, 0, orig_h).astype(int)

    keep = _nms(np.stack([x1, y1, x2, y2], axis=1), sc)

    return [
        {
            "label":  COCO_CLASSES[cids[i]],
            "box":    [int(x1[i]), int(y1[i]), int(x2[i]-x1[i]), int(y2[i]-y1[i])],
            "conf":   float(sc[i]),
            "threat": COCO_CLASSES[cids[i]] in HIGH_THREAT_LABELS,
        }
        for i in keep
    ]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Face recognition  — InsightFace buffalo_sc (ONNX, zero TensorFlow)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _norm(v: np.ndarray) -> np.ndarray:
    n = np.linalg.norm(v)
    return v / n if n > 1e-8 else v


def build_face_db() -> None:
    """
    Walk dataset/<identity_folder>/*.jpg|png
    Pre-compute L2-normalised MobileFaceNet embeddings per identity.
    Multiple identities supported — just add more sub-folders.
    """
    global admin_db
    if not os.path.exists(DATASET_DIR):
        print(f"[FaceDB] '{DATASET_DIR}' not found — create it with sub-folders of admin photos.")
        print("[FaceDB] Example:  dataset/Mahi_admin/photo1.jpg")
        return
    if face_app is None:
        return

    total_identities = 0
    for folder_name in os.listdir(DATASET_DIR):
        folder_path = os.path.join(DATASET_DIR, folder_name)
        if not os.path.isdir(folder_path):
            continue

        images = (glob.glob(os.path.join(folder_path, "*.jpg")) +
                  glob.glob(os.path.join(folder_path, "*.jpeg")) +
                  glob.glob(os.path.join(folder_path, "*.png")))

        embeddings = []
        for img_path in images:
            img = cv2.imread(img_path)
            if img is None:
                continue
            faces = face_app.get(img)
            if faces:
                embeddings.append(_norm(faces[0].embedding))

        if embeddings:
            admin_db[folder_name] = embeddings
            total_identities += 1
            print(f"[FaceDB] '{folder_name}': {len(embeddings)}/{len(images)} embeddings built.")
        else:
            print(f"[FaceDB] '{folder_name}': no faces detected in any image — skipping.")

    if total_identities == 0:
        print("[FaceDB] WARNING: No identities loaded. Add photos to dataset/ sub-folders.")
    else:
        print(f"[FaceDB] Ready with {total_identities} known identit{'y' if total_identities==1 else 'ies'}.")


def identify_faces(frame: np.ndarray) -> list[tuple[list[int], str]]:
    """
    Returns [(bbox_xyxy, identity_or_Unknown), ...] for every face in frame.
    Handles multiple people simultaneously.
    """
    if face_app is None or not admin_db:
        return []

    results = []
    for face in face_app.get(frame):
        emb = _norm(face.embedding)
        best_name, best_sim = "Unknown", -2.0

        for name, refs in admin_db.items():
            for ref_emb in refs:
                sim = float(np.dot(emb, ref_emb))
                if sim > best_sim:
                    best_sim = sim
                    if sim >= FACE_THRESHOLD:
                        best_name = name

        results.append((face.bbox.astype(int).tolist(), best_name))

    return results


def resolve_person_identity(person_box: list[int],
                            face_results: list[tuple[list[int], str]]) -> str:
    """Match a YOLO person box [x,y,w,h] to whichever face centre falls inside it."""
    px, py, pw, ph = person_box
    px2, py2 = px + pw, py + ph
    for (fx1, fy1, fx2, fy2), identity in face_results:
        if px <= (fx1+fx2)/2 <= px2 and py <= (fy1+fy2)/2 <= py2:
            return identity
    return "Unknown"


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Cloudinary helper
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def cdn_upload(frame: np.ndarray, folder: str, public_id: str, quality: int = 80):
    """Encode frame as JPEG and upload to the specified Cloudinary folder."""
    ok, buf = cv2.imencode(".jpg", frame, [cv2.IMWRITE_JPEG_QUALITY, quality])
    if not ok:
        return
    try:
        cloudinary.uploader.upload(
            buf.tobytes(),
            folder=folder,
            public_id=public_id,
            resource_type="image",
        )
    except Exception as exc:
        print(f"[CDN] Upload to '{folder}/{public_id}' failed: {exc}")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# App lifespan
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

@asynccontextmanager
async def lifespan(app: FastAPI):
    global yolo_session, face_app

    # ── YOLO ─────────────────────────────────────────────────────────────────
    if os.path.exists(YOLO_MODEL_PATH):
        yolo_session = ort.InferenceSession(
            YOLO_MODEL_PATH,
            providers=["CPUExecutionProvider"],
        )
        print(f"[YOLO] Loaded {YOLO_MODEL_PATH} — object detection ready.")
    else:
        print(f"[YOLO] '{YOLO_MODEL_PATH}' not found — object detection DISABLED.")

    # ── InsightFace ───────────────────────────────────────────────────────────
    try:
        from insightface.app import FaceAnalysis
        face_app = FaceAnalysis(name="buffalo_sc", providers=["CPUExecutionProvider"])
        face_app.prepare(ctx_id=-1, det_size=(320, 320))
        print("[FaceApp] InsightFace buffalo_sc ready.")
        build_face_db()
    except Exception as exc:
        print(f"[FaceApp] Load failed: {exc} — face recognition DISABLED.")

    gc.collect()
    print("[App] Startup complete. Serving requests.")
    yield
    print("[App] Shutdown.")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FastAPI
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
)

_api_key      = os.getenv("GEMINI_API_KEY")
gemini_client = genai.Client(api_key=_api_key) if _api_key else None

app = FastAPI(title="Edge Security API v2", version="2.0.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def root():
    return {
        "status":           "Edge Security API v2 — Online",
        "yolo_loaded":      yolo_session is not None,
        "face_app_loaded":  face_app is not None,
        "known_identities": list(admin_db.keys()),
        "gemini_ready":     gemini_client is not None,
        "cloudinary_folders": {
            "routine":  CDN_ROUTINE,
            "alerts":   CDN_ALERTS,
            "weapons":  CDN_WEAPONS,
        },
    }


@app.get("/health")
def health():
    """Keep-alive endpoint — frontend pings this every 10 min."""
    return {"status": "ok"}


@app.post("/api/analyze")
async def analyze_frame(file: UploadFile = File(...)):
    global _last_snapshot, _last_alert, _last_identity, _last_match_time

    raw   = await file.read()
    arr   = np.frombuffer(raw, np.uint8)
    frame = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    if frame is None:
        return {"error": "Invalid image — could not decode frame."}

    now = time.time()

    # ── 1. Object detection ───────────────────────────────────────────────────
    detections  = yolo_detect(frame)
    person_dets = [d for d in detections if d["label"] == "person"]
    threat_dets = [d for d in detections if d["threat"]]

    # ── 2. Face recognition ───────────────────────────────────────────────────
    face_results  = []
    identity_name = "Unknown"
    any_known     = False

    if person_dets:
        face_results = identify_faces(frame)

        for _, name in face_results:
            if name != "Unknown":
                _last_identity   = name
                _last_match_time = now
                any_known        = True

        # Grace period — hold identity to prevent flicker between frames
        if not any_known and (now - _last_match_time) < IDENTITY_GRACE:
            if _last_identity != "Unknown":
                face_results = [([0, 0, 1, 1], _last_identity)] + face_results
                any_known    = True

        identity_name   = _last_identity if any_known else "Unknown"
        _last_identity  = identity_name

    # ── 3. Per-person labelling ───────────────────────────────────────────────
    objects = []
    for d in detections:
        label = d["label"]
        if label == "person":
            pid   = resolve_person_identity(d["box"], face_results)
            label = f"Admin: {pid}" if pid != "Unknown" else "Unknown Human"
        objects.append({"label": label, "box": d["box"], "threat": d["threat"]})

    # ── 4. Threat scoring ─────────────────────────────────────────────────────
    unknown_intruder = any(o["label"] == "Unknown Human" for o in objects)
    if threat_dets:
        threat_level = "HIGH"
    elif unknown_intruder:
        threat_level = "MEDIUM"
    else:
        threat_level = "LOW"

    # ── 5. Cloudinary DVR (three separate organised folders) ──────────────────

    # 5-A  Routine heartbeat — every SNAPSHOT_INTERVAL seconds
    if now - _last_snapshot >= SNAPSHOT_INTERVAL:
        cdn_upload(frame, CDN_ROUTINE, f"frame_{int(now)}", quality=70)
        _last_snapshot = now

    # 5-B  Alert / weapon snapshot — with cooldown to avoid burst uploads
    if (unknown_intruder or threat_dets) and (now - _last_alert >= ALERT_COOLDOWN):
        af    = frame.copy()
        color = (0, 0, 255) if threat_dets else (0, 140, 255)
        cv2.rectangle(af, (0, 0), (af.shape[1], af.shape[0]), color, 10)
        msg = "WEAPON DETECTED" if threat_dets else "UNKNOWN INTRUDER"
        cv2.putText(af, f"ALERT: {msg}", (20, 56),
                    cv2.FONT_HERSHEY_DUPLEX, 1.2, color, 2)

        folder = CDN_WEAPONS if threat_dets else CDN_ALERTS
        cdn_upload(af, folder, f"alert_{int(now)}", quality=85)
        _last_alert = now

    return {
        "identity":       identity_name,
        "objects":        objects,
        "threat_level":   threat_level,
        "threat_objects": [d["label"] for d in threat_dets],
    }


@app.post("/api/gemini")
async def ask_gemini(file: UploadFile = File(...)):
    if not gemini_client:
        return {"response": "Gemini API key not configured.", "model_used": None}

    raw     = await file.read()
    pil_img = Image.open(io.BytesIO(raw)).convert("RGB")

    last_err = None
    for model_name in GEMINI_MODELS:
        try:
            resp = gemini_client.models.generate_content(
                model=model_name,
                contents=[SECURITY_PROMPT, pil_img],
            )
            if resp and resp.text:
                return {"response": resp.text.strip(), "model_used": model_name}
        except Exception as exc:
            print(f"[Gemini] '{model_name}' failed: {exc}")
            last_err = exc

    return {"response": f"All Gemini models unavailable: {last_err}", "model_used": None}