"""
Edge Security API v2
════════════════════════════════════════════════════════════════════════════════

Project file layout (flat — everything in one folder):
    main.py                 ← this file
    requirements.txt
    Dockerfile
    export_onnx.py          ← used by Docker stage 1 to generate yolov8n.onnx
    prebake_insightface.py  ← used by Docker stage 2 to pre-cache face models
    yolov8n.onnx            ← auto-generated by Docker build, do NOT commit
    index.html              ← frontend (deployed separately on Vercel)
    .env                    ← local secrets, never commit this

Admin identity photos live in Cloudinary (NOT in git):
    Cloudinary → admin_dataset/
                    Mahi_admin/     ← folder name = label shown on screen
                        photo1.jpg
                        photo2.jpg
                        ...         (20-30 photos recommended)
                    Another_Person/ ← add more folders for more identities
                        photo1.jpg

To add/remove a person: upload or delete their Cloudinary folder,
then redeploy (Render → Manual Deploy) — no code changes needed.

Cloudinary surveillance folders (auto-created on first upload):
    surveillance/routine/   ← heartbeat frame every 10 seconds
    surveillance/alerts/    ← snapshot when an unknown person is detected
    surveillance/weapons/   ← snapshot when a weapon-class object is detected

Environment variables required (set in Render dashboard + local .env):
    GEMINI_API_KEY
    CLOUDINARY_CLOUD_NAME
    CLOUDINARY_API_KEY
    CLOUDINARY_API_SECRET

RAM budget (fits Render / Koyeb 512 MB free tier):
    Python + FastAPI            ~  80 MB
    onnxruntime                 ~  60 MB
    InsightFace buffalo_sc      ~ 130 MB
    YOLOv8n ONNX inference      ~ 120 MB  (peak, sequential with face model)
    numpy / OpenCV / Pillow     ~  80 MB
    ─────────────────────────────────────
    Peak total                  ~ 470 MB  ✓
"""

import asyncio
import gc
import io
import os
import time
import urllib.request

import cv2
import cloudinary
import cloudinary.api
import cloudinary.uploader
import numpy as np
from contextlib import asynccontextmanager
from PIL import Image

from fastapi import BackgroundTasks, FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
from google import genai
import onnxruntime as ort

# Load .env first so all os.getenv() calls below see the values
load_dotenv()

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# File paths
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Absolute path to the folder containing this file (project root)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# yolov8n.onnx is placed here by the Docker builder stage — never commit it
YOLO_MODEL_PATH = os.path.join(BASE_DIR, "yolov8n.onnx")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Cloudinary folder names
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Root folder in Cloudinary that holds one sub-folder per known identity
CDN_ADMIN_ROOT = "admin_dataset"

# Surveillance recording folders (auto-created on first upload)
CDN_ROUTINE = "surveillance/routine"   # periodic heartbeat frames
CDN_ALERTS  = "surveillance/alerts"   # unknown person detected
CDN_WEAPONS = "surveillance/weapons"  # weapon-class object detected

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Tunable constants — adjust these without touching any logic
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Seconds between routine Cloudinary heartbeat snapshots
SNAPSHOT_INTERVAL = 10

# Minimum seconds between alert uploads to avoid burst-uploading the same event
ALERT_COOLDOWN = 15

# Seconds to keep showing a recognised identity after the last confirmed match.
# Prevents the label flickering on frames where the face is briefly occluded.
IDENTITY_GRACE = 3.0

# Cosine similarity threshold for InsightFace buffalo_sc MobileFaceNet embeddings.
# Range: [-1, 1]. Same person typically scores > 0.30.
# Raise toward 0.45 to reduce false positives (stricter).
# Lower toward 0.32 if the correct admin is being missed (more lenient).
FACE_THRESHOLD = 0.32

# YOLO detection confidence — detections below this are discarded
YOLO_CONF = 0.40

# ── COCO 80 class names — order must match YOLOv8n ONNX output tensor exactly ─
COCO_CLASSES = [
    "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train",
    "truck", "boat", "traffic light", "fire hydrant", "stop sign",
    "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", "cow",
    "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella", "handbag",
    "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite",
    "baseball bat", "baseball glove", "skateboard", "surfboard",
    "tennis racket", "bottle", "wine glass", "cup", "fork", "knife", "spoon",
    "bowl", "banana", "apple", "sandwich", "orange", "broccoli", "carrot",
    "hot dog", "pizza", "donut", "cake", "chair", "couch", "potted plant",
    "bed", "dining table", "toilet", "tv", "laptop", "mouse", "remote",
    "keyboard", "cell phone", "microwave", "oven", "toaster", "sink",
    "refrigerator", "book", "clock", "vase", "scissors", "teddy bear",
    "hair drier", "toothbrush",
]

# COCO labels that immediately escalate threat level to HIGH and
# trigger a weapon-alert snapshot upload to Cloudinary
HIGH_THREAT_LABELS = {"knife", "scissors", "baseball bat"}

# Gemini model fallback chain — tried in order until one succeeds.
# The original v1 code used invalid model names ("gemini-3.7-flash" etc.)
# which caused all Gemini calls to silently fail. These names are correct.
GEMINI_MODELS = [
    "gemini-2.5-flash",
    "gemini-2.0-flash",
    "gemini-1.5-flash",
]

# System prompt sent to Gemini with every frame for security analysis
SECURITY_PROMPT = (
    "You are a professional AI security analyst reviewing a live CCTV frame. "
    "Respond in ≤ 80 words covering: "
    "① how many people are visible and their behaviour, "
    "② any suspicious objects or activities, "
    "③ overall threat rating — LOW, MEDIUM, or HIGH — with one sentence of justification."
)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Global state — set once at startup, read-only during request handling
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ONNX inference session for YOLOv8n (set in lifespan)
yolo_session: ort.InferenceSession = None

# InsightFace FaceAnalysis app (set in lifespan)
face_app = None

# Face embedding database: {identity_folder_name: [normed_embedding, ...]}
# Built at startup by downloading photos from Cloudinary.
admin_db: dict[str, list[np.ndarray]] = {}

# Per-request mutable state for timing and identity grace period
_last_snapshot   = 0.0   # timestamp of last routine CDN upload
_last_alert      = 0.0   # timestamp of last alert CDN upload
_last_identity   = "Unknown"   # most recently confirmed identity name
_last_match_time = 0.0   # timestamp of last successful face match
_face_frame_skip = 0     # counter — face recognition runs every Nth frame only
_last_face_results: list = []  # cached face results reused between recognition frames

# How often to run InsightFace (every N frames).
# YOLO runs every frame (~300ms). InsightFace adds ~2s.
# At N=6: face ID runs ~once per 2-3s, YOLO detects instantly every frame.
FACE_RECOGNITION_EVERY_N = 6

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# YOLO object detection — pure ONNX Runtime, no PyTorch dependency
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _letterbox(frame: np.ndarray, size: int = 640):
    """
    Resize frame to size×size with letterbox padding (grey fill, top-left aligned).
    Returns (padded_frame, scale_factor) so detections can be mapped back to
    original pixel coordinates.
    """
    h, w    = frame.shape[:2]
    scale   = min(size / h, size / w)
    nw, nh  = int(w * scale), int(h * scale)
    resized = cv2.resize(frame, (nw, nh), interpolation=cv2.INTER_LINEAR)
    canvas  = np.full((size, size, 3), 114, dtype=np.uint8)
    canvas[:nh, :nw] = resized
    return canvas, scale


def _nms(boxes: np.ndarray, scores: np.ndarray, iou_thr: float = 0.45) -> list[int]:
    """
    Greedy non-maximum suppression.
    Keeps the highest-scoring box and removes any other box that overlaps it
    by more than iou_thr. Returns a list of kept indices.
    """
    x1, y1, x2, y2 = boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]
    areas = (x2 - x1 + 1) * (y2 - y1 + 1)
    order = scores.argsort()[::-1]
    keep  = []
    while order.size > 0:
        i = order[0]
        keep.append(i)
        xx1   = np.maximum(x1[i], x1[order[1:]])
        yy1   = np.maximum(y1[i], y1[order[1:]])
        xx2   = np.minimum(x2[i], x2[order[1:]])
        yy2   = np.minimum(y2[i], y2[order[1:]])
        inter = np.maximum(0.0, xx2 - xx1) * np.maximum(0.0, yy2 - yy1)
        iou   = inter / (areas[i] + areas[order[1:]] - inter)
        order = order[1:][iou < iou_thr]
    return keep


def yolo_detect(frame: np.ndarray) -> list[dict]:
    """
    Run YOLOv8n ONNX inference on a BGR frame.

    Returns a list of detections, each a dict:
        {
            "label":  str,          # COCO class name
            "box":    [x, y, w, h], # top-left origin, pixel coords
            "conf":   float,        # detection confidence 0-1
            "threat": bool,         # True if label is in HIGH_THREAT_LABELS,
        }
    Returns [] if the YOLO session failed to load at startup.
    """
    if yolo_session is None:
        return []

    orig_h, orig_w = frame.shape[:2]
    lb, scale = _letterbox(frame, size=640)

    # Build normalised NCHW blob: [1, 3, 640, 640], values in [0, 1]
    blob = lb.astype(np.float32) / 255.0
    blob = blob.transpose(2, 0, 1)[np.newaxis]

    inp  = yolo_session.get_inputs()[0].name
    raw  = yolo_session.run(None, {inp: blob})[0]   # shape: [1, 84, 8400]
    pred = raw[0].T                                  # shape: [8400, 84]

    # Columns 0-3: cx, cy, w, h (in letterboxed 640×640 space)
    # Columns 4-83: per-class scores for the 80 COCO classes
    cls_scores = pred[:, 4:]
    confidence = cls_scores.max(axis=1)
    class_ids  = cls_scores.argmax(axis=1)

    mask = confidence > YOLO_CONF
    
    print(f"[YOLO] Raw predictions: {pred.shape[0]}, Above threshold {YOLO_CONF}: {mask.sum()}")
    
    if not mask.any():
        print(f"[YOLO] No detections above confidence {YOLO_CONF}")
        return []

    p, sc, cids = pred[mask], confidence[mask], class_ids[mask]

    # Convert centre-form → corner-form and scale back to original pixel space
    cx = p[:, 0] / scale;  cy = p[:, 1] / scale
    bw = p[:, 2] / scale;  bh = p[:, 3] / scale
    x1 = np.clip(cx - bw / 2, 0, orig_w).astype(int)
    y1 = np.clip(cy - bh / 2, 0, orig_h).astype(int)
    x2 = np.clip(cx + bw / 2, 0, orig_w).astype(int)
    y2 = np.clip(cy + bh / 2, 0, orig_h).astype(int)

    keep = _nms(np.stack([x1, y1, x2, y2], axis=1), sc)

    detections = [
        {
            "label":  COCO_CLASSES[cids[i]],
            "box":    [int(x1[i]), int(y1[i]), int(x2[i] - x1[i]), int(y2[i] - y1[i])],
            "conf":   float(sc[i]),
            "threat": COCO_CLASSES[cids[i]] in HIGH_THREAT_LABELS,
        }
        for i in keep
    ]
    
    print(f"[YOLO] After NMS: {len(detections)} detections — {[d['label'] for d in detections]}")
    
    return detections


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Face recognition — InsightFace buffalo_sc (ONNX, zero TensorFlow)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _norm(v: np.ndarray) -> np.ndarray:
    """L2-normalise a vector. Returns the zero vector unchanged if norm ≈ 0."""
    n = np.linalg.norm(v)
    return v / n if n > 1e-8 else v


def build_face_db() -> None:
    """
    Download admin photos from Cloudinary at startup and build a face
    embedding database in memory.

    Cloudinary layout expected:
        admin_dataset/
            Mahi_admin/       ← sub-folder name becomes the identity label
                photo1.jpg
                photo2.jpg
                ...
            Another_Person/
                photo1.jpg

    Photos are downloaded via HTTPS, decoded with OpenCV, and processed by
    InsightFace to extract MobileFaceNet embeddings. Raw image bytes are
    discarded immediately — nothing is written to disk.

    To add a new person   → create a new sub-folder in Cloudinary + redeploy.
    To remove a person    → delete their Cloudinary sub-folder + redeploy.
    To update photos      → replace photos in Cloudinary + redeploy.
    Redeploy via          → Render dashboard → Manual Deploy.
    """
    global admin_db

    if face_app is None:
        print("[FaceDB] FaceApp not loaded — skipping database build.")
        return

    print(f"[FaceDB] Listing photos in Cloudinary '{CDN_ADMIN_ROOT}/'...")

    resources = []

    # Try every possible listing method and log all results for debugging
    print(f"[FaceDB] === Cloudinary diagnostic ===")
    print(f"[FaceDB] CDN_ADMIN_ROOT = '{CDN_ADMIN_ROOT}'")

    # Method 1: prefix
    try:
        r1 = cloudinary.api.resources(type="upload", prefix=CDN_ADMIN_ROOT + "/", max_results=500)
        items1 = r1.get("resources", [])
        print(f"[FaceDB] Method1 prefix='{CDN_ADMIN_ROOT}/': {len(items1)} items")
        for item in items1[:10]:
            print(f"[FaceDB]   public_id: {item.get('public_id')}")
        resources = items1
    except Exception as e:
        print(f"[FaceDB] Method1 failed: {e}")

    # Method 2: prefix without trailing slash
    if not resources:
        try:
            r2 = cloudinary.api.resources(type="upload", prefix=CDN_ADMIN_ROOT, max_results=500)
            items2 = r2.get("resources", [])
            print(f"[FaceDB] Method2 prefix='{CDN_ADMIN_ROOT}' (no slash): {len(items2)} items")
            for item in items2[:10]:
                print(f"[FaceDB]   public_id: {item.get('public_id')}")
            resources = items2
        except Exception as e:
            print(f"[FaceDB] Method2 failed: {e}")

    # Method 3: folder param
    if not resources:
        try:
            r3 = cloudinary.api.resources(type="upload", folder=CDN_ADMIN_ROOT, max_results=500)
            items3 = r3.get("resources", [])
            print(f"[FaceDB] Method3 folder='{CDN_ADMIN_ROOT}': {len(items3)} items")
            for item in items3[:10]:
                print(f"[FaceDB]   public_id: {item.get('public_id')}")
            resources = items3
        except Exception as e:
            print(f"[FaceDB] Method3 failed: {e}")

    # Method 4: list ALL resources and filter manually
    if not resources:
        try:
            r4 = cloudinary.api.resources(type="upload", max_results=500)
            all_items = r4.get("resources", [])
            print(f"[FaceDB] Method4 ALL resources: {len(all_items)} total in account")
            for item in all_items[:20]:
                print(f"[FaceDB]   public_id: {item.get('public_id')}")
            # Filter manually
            resources = [r for r in all_items if CDN_ADMIN_ROOT in r.get("public_id", "")]
            print(f"[FaceDB] After manual filter for '{CDN_ADMIN_ROOT}': {len(resources)} items")
        except Exception as e:
            print(f"[FaceDB] Method4 failed: {e}")

    print(f"[FaceDB] === End diagnostic, {len(resources)} resources to process ===")

    if not resources:
        print(f"[FaceDB] No photos found anywhere matching '{CDN_ADMIN_ROOT}'.")
        print(f"[FaceDB] Create folder admin_dataset/Mahi_admin in Cloudinary and upload photos.")
        return

    if not resources:
        print(f"[FaceDB] No photos found under Cloudinary '{CDN_ADMIN_ROOT}/'.")
        print("[FaceDB] Upload photos to Cloudinary → admin_dataset/<Your_Name>/photo.jpg")
        return

    # Group photo URLs by identity name.
    # Handle both path formats Cloudinary may return:
    #   Format A: "admin_dataset/Mahi_admin/photo1"  → parts[1] = "Mahi_admin"
    #   Format B: "Mahi_admin/photo1"                → parts[0] = "Mahi_admin"
    identity_map: dict[str, list[str]] = {}
    for res in resources:
        pid   = res.get("public_id", "")
        url   = res.get("secure_url", "")
        if not url:
            continue
        parts = pid.split("/")
        print(f"[FaceDB] Parsing public_id='{pid}' parts={parts}")

        if len(parts) >= 3 and parts[0] == CDN_ADMIN_ROOT:
            # Format A: admin_dataset/Mahi_admin/photo1
            identity_name = parts[1]
        elif len(parts) >= 3 and parts[0] != CDN_ADMIN_ROOT:
            # Format A variant: some_root/admin_dataset/Mahi_admin/photo1
            try:
                idx = parts.index(CDN_ADMIN_ROOT)
                identity_name = parts[idx + 1]
            except (ValueError, IndexError):
                continue
        elif len(parts) == 2:
            # Format B: Mahi_admin/photo1 (Cloudinary stripped the root)
            identity_name = parts[0]
        else:
            print(f"[FaceDB] Skipping unrecognised path format: '{pid}'")
            continue

        identity_map.setdefault(identity_name, []).append(url)

    if not identity_map:
        print("[FaceDB] No identity sub-folders found after parsing.")
        print("[FaceDB] Photos must be at: admin_dataset/<Name>/<photo>.jpg")
        print(f"[FaceDB] Got {len(resources)} resources but none matched expected structure.")
        return

    total_loaded = 0
    for identity_name, urls in identity_map.items():
        embeddings = []
        for url in urls:
            try:
                # Download photo bytes directly into memory — no temp files
                with urllib.request.urlopen(url, timeout=10) as resp:
                    img_bytes = resp.read()
                img_array = np.frombuffer(img_bytes, np.uint8)
                img = cv2.imdecode(img_array, cv2.IMREAD_COLOR)
                if img is None:
                    continue
                faces = face_app.get(img)
                if faces:
                    # Use the largest detected face (most likely the subject)
                    largest = max(faces, key=lambda f: (f.bbox[2]-f.bbox[0]) * (f.bbox[3]-f.bbox[1]))
                    embeddings.append(_norm(largest.embedding))
            except Exception as exc:
                print(f"[FaceDB]   ✗ {url.split('/')[-1]}: {exc}")
                continue

        if embeddings:
            admin_db[identity_name] = embeddings
            total_loaded += 1
            print(f"[FaceDB]   ✓ '{identity_name}': {len(embeddings)}/{len(urls)} embeddings built.")
        else:
            print(f"[FaceDB]   ✗ '{identity_name}': no faces detected in any photo — skipping.")

    if total_loaded == 0:
        print("[FaceDB] WARNING: No identities loaded. Verify photos contain visible faces.")
    else:
        suffix = "y" if total_loaded == 1 else "ies"
        print(f"[FaceDB] Ready — {total_loaded} known identit{suffix}: {list(admin_db.keys())}")


def identify_faces(frame: np.ndarray) -> list[tuple[list[int], str]]:
    """
    Detect all faces in a BGR frame and match each one against admin_db.

    Returns a list of (bbox, identity) tuples:
        bbox     → [x1, y1, x2, y2] in pixel coordinates
        identity → matched identity name, or "Unknown" if no match above threshold

    Supports multiple people in frame simultaneously — each face is matched
    independently against all known identities.
    """
    if face_app is None or not admin_db:
        return []

    results = []
    for face in face_app.get(frame):
        emb = _norm(face.embedding)
        best_name = "Unknown"
        best_sim  = -2.0    # cosine similarity range is [-1, 1]

        for name, refs in admin_db.items():
            for ref_emb in refs:
                # Dot product of two L2-normalised vectors = cosine similarity
                sim = float(np.dot(emb, ref_emb))
                if sim > best_sim:
                    best_sim = sim
                    if sim >= FACE_THRESHOLD:
                        best_name = name

        results.append((face.bbox.astype(int).tolist(), best_name))

    return results


def resolve_person_identity(
    person_box: list[int],
    face_results: list[tuple[list[int], str]],
) -> str:
    """
    Map a single YOLO person box [x, y, w, h] to an identity by finding
    the face whose centre-point lies inside the person bounding box.

    Returns the matched identity name or "Unknown" if no face centre
    falls inside the box (e.g. person detected but face not visible).
    """
    px, py, pw, ph = person_box
    px2, py2 = px + pw, py + ph

    for (fx1, fy1, fx2, fy2), identity in face_results:
        face_cx = (fx1 + fx2) / 2
        face_cy = (fy1 + fy2) / 2
        if px <= face_cx <= px2 and py <= face_cy <= py2:
            return identity

    return "Unknown"


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Cloudinary upload helper
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def cdn_upload(frame: np.ndarray, folder: str, public_id: str, quality: int = 80) -> None:
    """
    JPEG-encode a BGR frame and upload it to the specified Cloudinary folder.

    Args:
        frame:     OpenCV BGR image array
        folder:    Cloudinary folder path (e.g. "surveillance/alerts")
        public_id: Filename without extension (e.g. "alert_1720000000")
        quality:   JPEG quality 1-100 (lower = smaller file, faster upload)
    """
    ok, buf = cv2.imencode(".jpg", frame, [cv2.IMWRITE_JPEG_QUALITY, quality])
    if not ok:
        print(f"[CDN] Failed to encode frame for '{folder}/{public_id}'")
        return
    try:
        cloudinary.uploader.upload(
            buf.tobytes(),
            folder=folder,
            public_id=public_id,
            resource_type="image",
        )
    except Exception as exc:
        print(f"[CDN] Upload to '{folder}/{public_id}' failed: {exc}")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# App lifespan — model loading happens once at startup
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _probe_gemini_model() -> str | None:
    """
    At startup, find which Gemini model name actually works for this API key.
    Sends a tiny 1-token probe to each candidate — the first that succeeds
    is cached and reused for all subsequent /api/gemini requests.

    The google-genai SDK talks to v1beta by default. Model names returned by
    models.list() include a "models/" prefix AND may point to deprecated
    endpoints. This probe uses the exact same call path as ask_gemini so
    there are no surprises at request time.
    """
    # Candidates in preference order — adjust if Google releases newer versions
    # Model names taken directly from Google's 404 error messages:
    # "Please update your code to use models/gemini-3.6-flash"
    # Strip the "models/" prefix — generate_content needs just the name.
    candidates = [
        "gemini-3.6-flash",
        "gemini-3.5-flash-lite",
        "gemini-3.5-flash",
        "gemini-2.5-flash",
        "gemini-2.0-flash",
    ]
    probe_image = Image.new("RGB", (8, 8), color=(128, 128, 128))
    for name in candidates:
        try:
            resp = gemini_client.models.generate_content(
                model=name,
                contents=["Reply with one word: ok", probe_image],
            )
            if resp and resp.text:
                print(f"[Gemini] Working model: '{name}'")
                return name
        except Exception as exc:
            print(f"[Gemini] Probe '{name}' failed: {exc}")
    print("[Gemini] WARNING: No working Gemini model found. Check API key and quota.")
    return None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan context — runs startup code before the first request
    and teardown code after the last.

    Load order:
        1. Configure Cloudinary (credentials from env)
        2. Load YOLOv8n ONNX session
        3. Load InsightFace buffalo_sc models
        4. Fetch admin photos from Cloudinary and build embedding database
        5. Free build-time memory with gc.collect()
    """
    global yolo_session, face_app

    # ── 1. Cloudinary — configure inside lifespan so .env is already loaded ──
    cloudinary.config(
        cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
        api_key=os.getenv("CLOUDINARY_API_KEY"),
        api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    )

    # ── 2. YOLO ───────────────────────────────────────────────────────────────
    # yolov8n.onnx is copied into the image by the Docker builder stage.
    # On local dev: run `python export_onnx.py` once to generate it.
    if os.path.exists(YOLO_MODEL_PATH):
        yolo_session = ort.InferenceSession(
            YOLO_MODEL_PATH,
            providers=["CPUExecutionProvider"],
        )
        print(f"[YOLO] yolov8n.onnx loaded — object detection ready.")
    else:
        print(f"[YOLO] '{YOLO_MODEL_PATH}' not found — object detection DISABLED.")
        print("[YOLO] Run: python export_onnx.py  (requires: pip install ultralytics)")

    # ── 3. InsightFace ────────────────────────────────────────────────────────
    # buffalo_sc is pre-downloaded into the Docker image by prebake_insightface.py.
    # On local dev: first run auto-downloads ~67 MB of ONNX models to
    # ~/.insightface/models/buffalo_sc/ — this is cached for subsequent runs.
    try:
        from insightface.app import FaceAnalysis
        face_app = FaceAnalysis(name="buffalo_sc", providers=["CPUExecutionProvider"])
        face_app.prepare(ctx_id=-1, det_size=(320, 320))
        print("[FaceApp] InsightFace buffalo_sc loaded — face recognition ready.")

        # ── 4. Build face embedding database from Cloudinary photos ──────────
        # Run in a thread executor because build_face_db makes blocking
        # network calls (Cloudinary API + photo downloads) that would
        # stall the async event loop if called directly.
        await asyncio.get_event_loop().run_in_executor(None, build_face_db)

    except Exception as exc:
        print(f"[FaceApp] Failed to load InsightFace: {exc}")
        print("[FaceApp] Face recognition DISABLED.")

    # ── 5. Probe Gemini to find working model name at startup ────────────────
    global _working_gemini_model
    if gemini_client:
        _working_gemini_model = _probe_gemini_model()

    # ── 6. Release build-time allocations before serving requests ─────────────
    gc.collect()
    print("[App] Startup complete — serving requests.")

    yield   # ← application runs here, handling HTTP requests

    print("[App] Shutdown — goodbye.")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FastAPI application
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

_api_key      = os.getenv("GEMINI_API_KEY")
gemini_client = genai.Client(api_key=_api_key) if _api_key else None

# Pre-resolved model name — avoids calling models.list() on every request.
# Populated at startup in lifespan once we confirm which model works.
_working_gemini_model: str | None = None

app = FastAPI(title="Edge Security API v2", version="2.0.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # restrict to your Vercel domain in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def root():
    """Status endpoint — open this URL in a browser to verify the backend is running."""
    return {
        "status":           "Edge Security API v2 — Online",
        "yolo_loaded":      yolo_session is not None,
        "face_app_loaded":  face_app is not None,
        "known_identities": list(admin_db.keys()),
        "gemini_ready":     gemini_client is not None,
        "cloudinary_folders": {
            "admin_photos": CDN_ADMIN_ROOT,
            "routine":      CDN_ROUTINE,
            "alerts":       CDN_ALERTS,
            "weapons":      CDN_WEAPONS,
        },
    }


@app.get("/health")
def health():
    """
    Lightweight keep-alive endpoint.
    The Vercel frontend pings this every 10 minutes to prevent Render's
    free-tier service from spinning down due to inactivity.
    """
    return {"status": "ok"}


@app.get("/api/debug-cloudinary")
def debug_cloudinary():
    """
    Debug endpoint — shows exactly what Cloudinary returns for the admin_dataset folder.
    Open this in your browser if known_identities is empty.
    Tells you whether credentials are wrong, folder is empty, or path is mismatched.
    """
    try:
        result = cloudinary.api.resources(
            type="upload",
            prefix=CDN_ADMIN_ROOT + "/",
            max_results=100,
        )
        resources = result.get("resources", [])
        # Group by identity sub-folder for easier reading
        by_identity = {}
        for r in resources:
            parts = r["public_id"].split("/")
            identity = parts[1] if len(parts) >= 3 else "__root__"
            by_identity.setdefault(identity, []).append(r["public_id"])

        return {
            "status":           "ok",
            "cdn_admin_root":   CDN_ADMIN_ROOT,
            "total_found":      len(resources),
            "by_identity":      {k: len(v) for k, v in by_identity.items()},
            "public_ids":       [r["public_id"] for r in resources[:20]],
            "admin_db_keys":    list(admin_db.keys()),
            "gemini_model":     _working_gemini_model,
            "hint": (
                f"Photos must be at: {CDN_ADMIN_ROOT}/<YourName>/photo.jpg  "
                "The folder directly under admin_dataset becomes the identity label. "
                "If total_found is 0, create the folder structure in Cloudinary first."
            ),
        }
    except Exception as exc:
        return {
            "status":  "error",
            "message": str(exc),
            "hint":    "Check CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET in Render env vars.",
        }


@app.post("/api/reload-faces")
async def reload_faces():
    """
    Force a rebuild of the face embedding database from Cloudinary.
    Call this after uploading new admin photos without redeploying.
    Example: POST https://your-app.onrender.com/api/reload-faces
    """
    global admin_db
    admin_db = {}  # Clear existing database
    await asyncio.get_event_loop().run_in_executor(None, build_face_db)
    return {
        "status":           "reloaded",
        "known_identities": list(admin_db.keys()),
        "total_embeddings": {k: len(v) for k, v in admin_db.items()},
    }


@app.post("/api/analyze")
async def analyze_frame(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    """
    Main analysis endpoint — called by the frontend every ~900 ms with
    a JPEG frame captured from the webcam.

    Pipeline:
        1. Decode the uploaded JPEG frame
        2. Run YOLOv8n to detect all objects
        3. If any person is detected, run InsightFace to recognise faces
        4. Apply identity grace period to prevent label flickering
        5. Map each YOLO person box to its face identity
        6. Compute threat level: LOW / MEDIUM / HIGH
        7. Schedule Cloudinary uploads as background tasks (non-blocking)
        8. Return structured JSON to the frontend immediately

    Cloudinary uploads are offloaded to background threads via BackgroundTasks
    so they never block the event loop or freeze the camera feed.

    Returns:
        {
            "identity":       str,          # name of recognised admin or "Unknown"
            "objects":        [...],        # list of detected objects with labels and boxes
            "threat_level":   str,          # "LOW", "MEDIUM", or "HIGH"
            "threat_objects": [str, ...],   # names of weapon-class objects detected
        }
    """
    global _last_snapshot, _last_alert, _last_identity, _last_match_time

    # Decode uploaded JPEG bytes into an OpenCV BGR frame
    raw   = await file.read()
    arr   = np.frombuffer(raw, np.uint8)
    frame = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    if frame is None:
        return {"error": "Invalid image — could not decode the uploaded frame."}

    now = time.time()

    # ── Step 1: Object detection ──────────────────────────────────────────────
    detections  = yolo_detect(frame)
    person_dets = [d for d in detections if d["label"] == "person"]
    threat_dets = [d for d in detections if d["threat"]]

    # ── Step 2: Face recognition (decimated — runs every N frames) ──────────
    # YOLO (~300ms) runs every frame for instant detection.
    # InsightFace (~2s) only runs every FACE_RECOGNITION_EVERY_N frames.
    # Between recognition frames, the last known identity is reused so the
    # label never disappears — it just updates less frequently.
    global _face_frame_skip, _last_face_results

    face_results  = []
    identity_name = "Unknown"
    any_known     = False

    if person_dets:
        _face_frame_skip += 1

        if _face_frame_skip >= FACE_RECOGNITION_EVERY_N:
            # Run full face recognition this frame
            _face_frame_skip  = 0
            _last_face_results = identify_faces(frame)

        # Use either fresh results or cached results from last recognition frame
        face_results = _last_face_results

        # Check for a known identity in current face results
        for _, name in face_results:
            if name != "Unknown":
                _last_identity   = name
                _last_match_time = now
                any_known        = True
                break

        # Grace period: carry last known identity forward to prevent flicker
        if not any_known and (now - _last_match_time) < IDENTITY_GRACE:
            if _last_identity != "Unknown":
                face_results = [([0, 0, 1, 1], _last_identity)] + face_results
                any_known    = True

        identity_name  = _last_identity if any_known else "Unknown"
        _last_identity = identity_name

    else:
        # No person visible — reset state
        _face_frame_skip   = 0
        _last_face_results = []
        _last_identity     = "Unknown"
        identity_name      = "Unknown"

    # ── Step 3: Per-person labelling ──────────────────────────────────────────
    # Each YOLO detection keeps its original label except "person" boxes,
    # which get labelled with the matched identity or "Unknown Human".
    objects = []
    for d in detections:
        label = d["label"]
        if label == "person":
            pid   = resolve_person_identity(d["box"], face_results)
            label = f"Admin: {pid}" if pid != "Unknown" else "Unknown Human"
        objects.append({"label": label, "box": d["box"], "threat": d["threat"]})

    # ── Step 4: Threat level scoring ──────────────────────────────────────────
    unknown_intruder = any(o["label"] == "Unknown Human" for o in objects)
    if threat_dets:
        threat_level = "HIGH"     # weapon-class object detected
    elif unknown_intruder:
        threat_level = "MEDIUM"   # unrecognised person detected
    else:
        threat_level = "LOW"      # only known admins or no people

    # ── Step 5: Cloudinary DVR uploads ────────────────────────────────────────
    # Both uploads are scheduled as background tasks so they run AFTER the
    # response is already sent to the frontend. This means the camera feed
    # never freezes waiting for a Cloudinary network call to finish.

    # 5-A: Routine heartbeat — one frame every SNAPSHOT_INTERVAL seconds
    if now - _last_snapshot >= SNAPSHOT_INTERVAL:
        background_tasks.add_task(cdn_upload, frame, CDN_ROUTINE, f"frame_{int(now)}", 70)
        _last_snapshot = now

    # 5-B: Alert snapshot — triggered by unknown intruder or weapon detection.
    # ALERT_COOLDOWN prevents duplicate uploads for the same ongoing event.
    if (unknown_intruder or threat_dets) and (now - _last_alert >= ALERT_COOLDOWN):
        alert_frame = frame.copy()
        # Red border for weapons, orange for unknown intruder
        color = (0, 0, 255) if threat_dets else (0, 140, 255)
        cv2.rectangle(alert_frame, (0, 0), (alert_frame.shape[1], alert_frame.shape[0]), color, 10)
        msg = "WEAPON DETECTED" if threat_dets else "UNKNOWN INTRUDER"
        cv2.putText(alert_frame, f"ALERT: {msg}", (20, 56),
                    cv2.FONT_HERSHEY_DUPLEX, 1.2, color, 2)

        folder = CDN_WEAPONS if threat_dets else CDN_ALERTS
        background_tasks.add_task(cdn_upload, alert_frame, folder, f"alert_{int(now)}", 85)
        _last_alert = now

    return {
        "identity":       identity_name,
        "objects":        objects,
        "threat_level":   threat_level,
        "threat_objects": [d["label"] for d in threat_dets],
    }


@app.post("/api/gemini")
def ask_gemini(file: UploadFile = File(...)):
    """
    On-demand Gemini AI analysis endpoint — sync so FastAPI runs it in a
    thread pool, keeping the event loop free during the 5-15s Gemini call.

    Uses _working_gemini_model probed at startup — no per-request model
    discovery, no deprecated name issues, no models/ prefix confusion.
    """
    if not gemini_client:
        return {"response": "Gemini API key not configured.", "model_used": None}

    if not _working_gemini_model:
        return {
            "response": (
                "No working Gemini model found. Check your GEMINI_API_KEY "
                "in Render environment variables and verify the key has "
                "access to Gemini Flash models at aistudio.google.com."
            ),
            "model_used": None,
        }

    raw     = file.file.read()
    pil_img = Image.open(io.BytesIO(raw)).convert("RGB")

    try:
        resp = gemini_client.models.generate_content(
            model=_working_gemini_model,
            contents=[SECURITY_PROMPT, pil_img],
        )
        if resp and resp.text:
            return {"response": resp.text.strip(), "model_used": _working_gemini_model}
        return {"response": "Empty response from Gemini.", "model_used": _working_gemini_model}
    except Exception as exc:
        print(f"[Gemini] generate_content failed: {exc}")
        return {
            "response":   f"Gemini request failed: {exc}",
            "model_used": None,
        }